# =============================================================================
# EMBEDDING PIPELINE CONFIGURATION
# =============================================================================
# Pure config-driven approach with variable references and no duplication
# All parameters defined once and referenced throughout the configuration

# =============================================================================
# JOB CONFIGURATION - Base settings for the entire pipeline
# =============================================================================
job:
  name: "embedding_generation_example"
  output_dir: "examples/outputs"
  random_seed: 42

# =============================================================================
# INPUT CONFIGURATION - Data source settings
# =============================================================================
input:
  dataset_path: "data/medical_claims_sample.csv"

# =============================================================================
# MODEL API CONFIGURATION - Connection settings for MediClaimGPT
# =============================================================================
model_api:
  base_url: "http://localhost:8000"
  timeout: 300
  max_retries: 3
  endpoints:
    embeddings_batch: "/embeddings_batch"

# =============================================================================
# EMBEDDING GENERATION CONFIGURATION - Core processing settings
# =============================================================================
embedding_generation:
  batch_size: 8
  max_sequence_length: 1024
  padding_side: "left"
  truncation_side: "left"
  tokenizer_path: "/home/kosaraju/mgpt-serve/tokenizer"
  output_filename: "${job.name}_embeddings.csv"

# =============================================================================
# OUTPUT CONFIGURATION - Directory structure using variable references
# =============================================================================
output:
  embeddings_dir: "${job.output_dir}/embeddings"
  logs_dir: "${job.output_dir}/logs"

# =============================================================================
# LOGGING CONFIGURATION - Using template references for log file path
# =============================================================================
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "${output.logs_dir}/embedding_pipeline.log"

# =============================================================================
# CONFIGURATION NOTES
# =============================================================================
# Variable References Used:
# - ${job.name} -> "embedding_generation_example"
# - ${job.output_dir} -> "examples/outputs"
# - ${output.logs_dir} -> "examples/outputs/logs"
# 
# API Format Compatible with:
# curl -X POST http://localhost:8000/embeddings_batch \
#   -H "Content-Type: application/json" \
#   -d '{
#     "claims": ["claim1", "claim2"],
#     "padding_side": "left",
#     "truncation_side": "left",
#     "max_length": 1024
#   }'
#
# Key Simplifications:
# - No splitting configuration (handled downstream)
# - No checkpoint/resume functionality 
# - Single batch_size parameter
# - Single random_seed parameter
# - Relative paths with variable references
# - Embedding-only pipeline focus